spring:
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:DBPERSONS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true


server:
  port: 9010